import { Log } from './logger.js';

const token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJha2FzaGFybWEzMTdAZ21haWwuY29tIiwiZXhwIjoxNzUyNDcxMjk5LCJpYXQiOjE3NTI0NzAzOTksImlzcyI6IkFmZm9yZCBNZWRpY2FsIFRlY2hub2xvZ2llcyBQcml2YXRlIExpbWl0ZWQiLCJqdGkiOiI3NDhlNTk5MC1iMTIyLTRmNzYtYWE5Mi0wMGNjNGQyZDdmYzYiLCJsb2NhbGUiOiJlbi1JTiIsIm5hbWUiOiJha2FzaGRlZXAgc2hhcm1hIiwic3ViIjoiYmE2ZjIyYzctZDkyZS00ODMzLWE1NzgtODdiODAxNGI1MTZkIn0sImVtYWlsIjoiYWthc2hhcm1hMzE3QGdtYWlsLmNvbSIsIm5hbWUiOiJha2FzaGRlZXAgc2hhcm1hIiwicm9sbE5vIjoiMTIyMTYzOTMiLCJhY2Nlc3NDb2RlIjoiQ1p5cFFLIiwiY2xpZW50SUQiOiJiYTZmMjJjNy1kOTJlLTQ4MzMtYTU3OC04N2I4MDE0YjUxNmQiLCJjbGllbnRTZWNyZXQiOiJCTWpDblJmZ1VHUlVBUmVzIn0.tgg1PJ4DmKfWcspHFHNudJWMYKYLoYCTzpgBj64PEh8'; 

Log("frontend", "info", "component", "User opened the homepage", token);
